[[constraint]]
  name = "gopkg.in/yaml.v2"
  version = "2.2.1"

[[constraint]]
  name = "github.com/stretchr/testify"
  version = "1.2.2"

[[constraint]]
  name = "github.com/fatih/color"
  version = "1.7.0"

[[constraint]]
  name = "github.com/hpcloud/tail"
  branch = "master"

[[constraint]]
  name = "github.com/emirpasic/gods"
  version = "1.12.0"